<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0;net10.0-android;net10.0-ios</TargetFrameworks>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<RootNamespace>AirshipDotNet.CustomViews</RootNamespace>
		<IsTrimmable>false</IsTrimmable>
		<UseMaui>true</UseMaui>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">16.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">26.0</SupportedOSPlatformVersion>
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>Airship.Net.CustomViews</PackageId>
		<Title>Airship Custom Views SDK</Title>
		<Summary>Airship Scenes custom view SDK .NET Library</Summary>
		<Description>Register MAUI views that Airship Scenes can render inline</Description>
		<AssemblyVersion>$(AirshipCrossPlatformVersion)</AssemblyVersion>
		<PackageVersion>$(AirshipCrossPlatformNugetVersion)</PackageVersion>
		<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-ios|AnyCPU'">
	  <CreatePackage>false</CreatePackage>
	  <MtouchHttpClientHandler>HttpClientHandler</MtouchHttpClientHandler>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Platforms/Android/**" Condition="'$(TargetFramework)' != 'net10.0-android'" />
		<Compile Remove="Platforms/iOS/**" Condition="'$(TargetFramework)' != 'net10.0-ios'" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.110" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Airship.Net\Airship.Net.csproj" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0-android'">
		<ProjectReference Include="..\..\binderator\generated\Airship.Net.Android.Layout\Airship.Net.Android.Layout.csproj" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0-ios'">
		<ProjectReference Include="..\AirshipBindings.iOS.ObjectiveC\AirshipBindings.iOS.ObjectiveC.csproj" />
	</ItemGroup>

</Project>
